/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spiritgraahknatures;

import java.util.Arrays;

/**
 *
 * @author VOLT
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pouchTable = new javax.swing.JTable();
        renewUsingPots = new javax.swing.JCheckBox();
        teleportingMethod = new javax.swing.JComboBox();
        repairingMethod = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Spirit Graahk Natures ExKALLEBur");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pouchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Massive",  new Boolean(false)},
                {"Giant",  new Boolean(true)},
                {"Large",  new Boolean(true)},
                {"Medium",  new Boolean(true)},
                {"Small",  new Boolean(true)}
            },
            new String [] {
                "Pouch", "Enable?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pouchTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pouchTableFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(pouchTable);

        renewUsingPots.setText("Renew points using pots (will use obby if not)");
        renewUsingPots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renewUsingPotsActionPerformed(evt);
            }
        });

        teleportingMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dueling ring", "Ring Of Kinship" }));
        teleportingMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teleportingMethodActionPerformed(evt);
            }
        });

        repairingMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NPC Contact", "Wicked Hat" }));
        repairingMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repairingMethodActionPerformed(evt);
            }
        });

        jLabel1.setText("Bank method");

        jLabel2.setText("Repairing method");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(renewUsingPots)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(teleportingMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(52, 52, 52)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(repairingMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(14, 14, 14))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teleportingMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repairingMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(renewUsingPots)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void renewUsingPotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renewUsingPotsActionPerformed
        Data.usePots = renewUsingPots.isSelected();
    }//GEN-LAST:event_renewUsingPotsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        renewUsingPotsActionPerformed(null);
        teleportingMethodActionPerformed(null);
        pouchTableFocusLost(null);
        repairingMethodActionPerformed(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void teleportingMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teleportingMethodActionPerformed
        Data.bankTeleMethod = teleportingMethod.getSelectedIndex();
    }//GEN-LAST:event_teleportingMethodActionPerformed

    private void repairingMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repairingMethodActionPerformed
        Data.repairingMethod = repairingMethod.getSelectedIndex();
    }//GEN-LAST:event_repairingMethodActionPerformed

    private void pouchTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pouchTableFocusLost
        int max = pouchTable.getModel().getRowCount();
        for (int i = 0; i < max; i++) {
            boolean b = (boolean) pouchTable.getModel().getValueAt(i, 1);
            Data.POUCHES.values()[i].setEnabled(b);
        }
        System.out.println(Arrays.toString(Data.POUCHES.values()));
        SpiritGraahkNatures.started = true;
    }//GEN-LAST:event_pouchTableFocusLost
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable pouchTable;
    private javax.swing.JCheckBox renewUsingPots;
    private javax.swing.JComboBox repairingMethod;
    private javax.swing.JComboBox teleportingMethod;
    // End of variables declaration//GEN-END:variables
}
